In [1]:
# NUMPY SPECIAL OPERATIONS
# Import libraries

import numpy as np

# numpy array is homogenous, whereas python list is heterogenous

In [22]:
arr1= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]], [[13,14,15],[16,17,18]]]) # declaring array 1
arr2= np.array([[[19,20,21],[22,23,24]],[[25,26,27],[28,29,30]]]) # declaring array 2
print("Shape of array 1",arr1.shape) # shape of the array
print("Shape of array 2",arr2.shape)  # shape of the array
print("Concatenated array 1 and array 2: \n",np.concatenate((arr1,arr2), axis=0)) # concatenate two arrays
print("Shape of concatenated array 1 and array 2: \n",np.concatenate((arr1,arr2), axis=0).shape) # concatenate two arrays
# axis=0 → Operate along rows (apply the function to each column).

Shape of array 1 (3, 2, 3)
Shape of array 2 (2, 2, 3)
Concatenated array 1 and array 2: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]]]
Shape of concatenated array 1 and array 2: 
 (5, 2, 3)


In [3]:
# Creating two 3D numpy arrays with compatible shapes

arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr4= np.array([[[19, 20, 21], [22, 23, 24]], [[25, 26, 27], [28, 29, 30]]])

In [4]:
# Printing the shape of the arrays

print("Shape of array 3",arr3.shape) # shape of the array
print("Shape of array 4",arr4.shape)  # shape of the array

Shape of array 3 (2, 2, 3)
Shape of array 4 (2, 2, 3)


In [5]:
# Adding the two arrays

print(arr3 + arr4)

[[[20 22 24]
  [26 28 30]]

 [[32 34 36]
  [38 40 42]]]


In [6]:
# Concatenating the two arrays along the first axis

print("Shape of concatenated array 3 and array 4",np.concatenate((arr3, arr4), axis=1).shape)  
# axis=1 → Operate along columns (apply the function to each row).
arr5=np.array([[[1,2,3,4,5,6,7,8,4,8768,78,88]]])
print("The array is",arr5)
print("The shape of the array is",arr5.shape)

Shape of concatenated array 3 and array 4 (2, 4, 3)
The array is [[[   1    2    3    4    5    6    7    8    4 8768   78   88]]]
The shape of the array is (1, 1, 12)


In [7]:
# Creating a 3x3 array of zeros

arr1 = np.zeros([3, 3]) 
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# Creating a 3x3 array of ones

arr2 = np.ones([3, 3])
print(arr2)

arr3=np.full([3,3],'Soumya')
print(arr3)

arr4=np.arange(1,101,4)
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[['Soumya' 'Soumya' 'Soumya']
 ['Soumya' 'Soumya' 'Soumya']
 ['Soumya' 'Soumya' 'Soumya']]
[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]


In [9]:

# NUMPY RANDOM OPERATIONS

from numpy import random

arr5=random.randint(50,100,size=6)
print(arr5)

[93 51 83 66 93 50]


In [10]:
arr6=random.randint(50,100,size=(3,3))
print(arr6)

[[59 53 92]
 [64 55 58]
 [80 50 64]]


In [11]:
arr7=random.rand(1)
print(arr7)

[0.47721508]


In [12]:
arr8=random.rand(4,3,4)
print(arr8)

[[[0.24256392 0.30754828 0.47291755 0.58313368]
  [0.62770156 0.49779161 0.7571068  0.03890479]
  [0.16967134 0.1210235  0.47874627 0.05700443]]

 [[0.62430381 0.61838509 0.85198466 0.36438823]
  [0.20500604 0.2390048  0.46435418 0.40450451]
  [0.87049078 0.76822503 0.15455029 0.03193748]]

 [[0.56194393 0.18551231 0.44102782 0.86066329]
  [0.91460527 0.07887928 0.7775929  0.77566356]
  [0.54671561 0.07745105 0.89754783 0.18710699]]

 [[0.23991613 0.45178349 0.81878681 0.02928563]
  [0.69665847 0.85432071 0.07653981 0.70923183]
  [0.78502976 0.95630228 0.63236238 0.25150732]]]


In [13]:
arr9=random.uniform(10,20,size=7)
print(arr9)

[10.06421158 18.49586957 18.38956786 18.06040426 10.16142314 10.28001756
 16.30235857]


In [14]:
arr10=random.choice([1,4,5,3,24,54,3],size=(4,4))
print(arr10)

[[54  3 24  5]
 [54  1  4  4]
 [ 4  3 24  5]
 [ 4  3  3 54]]


In [15]:
arr11=np.array([1,2,3,4,5,7])**4
print(arr11)
print(len(arr11))


[   1   16   81  256  625 2401]
6


In [16]:
arr12=np.sum([1,2,3,4,5,7])
print(arr12)

22


In [17]:
arr13=np.median([1,2,3,4,5,7])
print(arr13)

3.5


In [18]:
arr14=np.median([1,2,3,4,5,7])
print(arr14)

3.5


In [19]:
arr15=np.std([1,2,3,4,5,7])
print(arr15)

1.9720265943665387


In [20]:
arr16=np.var([1,2,3,4,5,7])
print(arr16)

3.8888888888888893
